on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: bin/set-tag >> "$GITHUB_ENV"
    - run: bin/build "$TAG"
    - run: bin/test "$TAG"
    - uses: actions/checkout@v3
      with:
        ref: info
        token: ${{ secrets.GITHUB_TOKEN }}
        path: info
      if: github.event_name != 'pull_request'
    - run: bin/push info "$TAG"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ECR_DEPLOY_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_DEPLOY_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        GHCR_USER: ${{ github.actor }}
        GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'pull_request'
