on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: bin/set-tag >> "$GITHUB_ENV"
    - run: bin/build "$TAG"
    - run: bin/test "$TAG"
    - uses: actions/checkout@v3
      with:
        ref: info
        token: ${{ secrets.GITHUB_TOKEN }}
        path: info
      if: github.event_name != 'pull_request'
    - uses: pre-commit-ci/configure-aws-credentials@7fc5f080e5992f77207d1ea0a8d33d4bcd1c80c8
      with:
        role-to-assume: ${{ secrets.ECR_DEPLOY_ROLE_ARN }}
        aws-region: us-east-1
      if: github.event_name != 'pull_request'
    - run: bin/push info "$TAG"
      env:
        GHCR_USER: ${{ github.actor }}
        GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'pull_request'
